### ISSUE TITLE
Building for minGW

### ISSUE THREAD

**Issue by ivandmitrievsky** [H2CO3/Sparkling#29]
Hi, thank you for creating Sparkling! :star: 
Have you ever tried building it on Windows machine with [MinGW](http://www.mingw.org/) installed?

**Comment by H2CO3** [comment]
Hi!

You're welcome. Yes, I've tried a few times, and it builds and runs nicely :)

**Comment by ivandmitrievsky** [comment]
A couple of months ago I was trying to build it and was getting an error at [this](https://github.com/H2CO3/Sparkling/blob/f8916f220632a43b9ad07fce9282420cf55a54e0/src/rtlb.c#L3793) line.

I think it was something related to MinGW not having `nanosleep` function. My solution was to simply swap `#if` branches, because MinGW `#define`s `_WIN32`. After this change compiler started complaining about not having `Sleep` function, so I also added:
```c
#ifdef _WIN32
#include <windows.h>
#endif
```
to file's `#include`s.

Sorry for so vague explanation and not providing a pull request :disappointed: I don't have an access to any Windows testing environment, but these details just popped into my head and I decided to share with you :blush: 

If I was only one to experience these troubles then it's up to you if this code needs to be updated. I don't see any harm in doing so.

**Comment by H2CO3** [comment]
fixed in https://github.com/H2CO3/Sparkling/commit/8e418cf7f259a88327af52cbcd0f321312956032.
