### ISSUE TITLE
REPL is broken

### ISSUE THREAD

**Issue by ghost** [H2CO3/Sparkling#48]
@jcubic @H2CO3 @mattfenwick @sfan5 @idmitrievsky 

**1.** Variables not saved:

```
Sparkling build 89061a2, copyright (C) 2013-2017, Árpád Goretity

spn:1> let a = 0;
spn:2> print(a);
global 'a' does not exist or it is nil
Runtime error, call stack:

	[0   ] <main program> in ???: line 1 char 7 near 0x5

```

**2.** Only can write in one line:

```
Sparkling build 89061a2, copyright (C) 2013-2017, Árpád Goretity

spn:1> fn say_hello(name) {
near line 1, char 20: expecting '}' at end of block

spn:2> 
```

**OS:** MacOS 10.13.6
**CPU:** i386
**Compiler:** Apple LLVM version 7.0.2 (clang-700.1.81)

**Comment by H2CO3** [comment]
The REPL is not "broken". Variables declared with `let` are locals, if you want globals, use `const`. Multi-line commands are a separate feature request, that hardly counts as "broken", either.
